spring:
  application:
    name: acknowledgehub

  datasource:
    url: jdbc:mysql://localhost:3306/acknowledge_hub_db
    username: root
    password: root

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        callable: false
    hibernate:
      ddl-auto: update
