spring:
  application:
    name: acknowledgehub
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3306/acknowledge_hub_db
    username: root
    password: root

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        callable: false
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  address: 0.0.0.0
  port: 8080

app:
  api:
    base-url: /api/v1 #Format is /*/*

telegram:
  bot:
    username: telegram bot name 
    token: telegram bot token

#if u need to debug spring security u can use this property.
logging:
  level:
    org.springframework.security: DEBUG

